// prototype/src/pages/SettingsPage.vue
<script setup lang="ts">
import { ref } from 'vue'

const notifications = ref(true)
const darkMode = ref(false)
</script>

<template>
  <form class="space-y-4 max-w-md">
    <div class="form-control">
      <label class="label cursor-pointer">
        <span class="label-text">Enable notifications</span>
        <input type="checkbox" v-model="notifications" class="toggle" />
      </label>
    </div>
    <div class="form-control">
      <label class="label cursor-pointer">
        <span class="label-text">Dark mode</span>
        <input type="checkbox" v-model="darkMode" class="toggle" />
      </label>
    </div>
    <button class="btn btn-primary btn-sm" type="submit">Save</button>
  </form>
</template>

// lib/src/pages/SettingsPage.tsx
import { useState } from 'react'

export default function SettingsPage() {
  const [notifications, setNotifications] = useState(true)
  const [darkMode, setDarkMode] = useState(false)

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    // Handle form submission here
    console.log('Settings saved:', { notifications, darkMode })
  }

  return (
    <div className="flex justify-center  p-4">
      <form className="space-y-4 max-w-md" onSubmit={handleSubmit}>
        <div className="form-control">
          <label className="label cursor-pointer">
            <span className="label-text">Enable notifications</span>
            <input 
              type="checkbox" 
              checked={notifications}
              onChange={(e) => setNotifications(e.target.checked)}
              className="toggle" 
            />
          </label>
        </div>
        <div className="form-control">
          <label className="label cursor-pointer">
            <span className="label-text">Dark mode</span>
            <input 
              type="checkbox" 
              checked={darkMode}
              onChange={(e) => setDarkMode(e.target.checked)}
              className="toggle" 
            />
          </label>
        </div>
        <button className="btn btn-primary btn-sm" type="submit">
          Save
        </button>
      </form>
    </div>
  )
}
