// prototype/src/components/Sidebar.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { HomeIcon, MapIcon, UsersIcon, UserGroupIcon, ShoppingBagIcon, CalendarIcon } from '@heroicons/vue/24/outline';

defineProps<{ open: boolean }>()
</script>

<template>
  <div
    :class="[
      'h-full bg-base-100 z-30 shadow-lg overflow-hidden transition-[width] duration-300',
      open ? 'w-58' : 'w-0'
    ]"
  >
    <ul v-if="open" class="menu text-base-content min-h-full w-full p-4">
      <li><RouterLink to="/" class="flex items-center gap-2"><HomeIcon class="size-5" />Feed</RouterLink></li>
      <li><RouterLink to="/map" class="flex items-center gap-2"><MapIcon class="size-5" />Map</RouterLink></li>
      <li><RouterLink to="/friends" class="flex items-center gap-2"><UsersIcon class="size-5" />Friends</RouterLink></li>
      <li><RouterLink to="/groups" class="flex items-center gap-2"><UserGroupIcon class="size-5" />Groups</RouterLink></li>
      <li><RouterLink to="/market" class="flex items-center gap-2"><ShoppingBagIcon class="size-5" />Market</RouterLink></li>
      <li><RouterLink to="/calendar" class="flex items-center gap-2"><CalendarIcon class="size-5" />Calendar</RouterLink></li>
    </ul>
  </div>
</template>

// lib/src/components/Sidebar.tsx
import { Link } from 'react-router-dom'
import { 
  HomeIcon, 
  MapIcon, 
  UsersIcon, 
  UserGroupIcon, 
  ShoppingBagIcon, 
  CalendarIcon 
} from '@heroicons/react/24/outline'

interface SidebarProps {
  open: boolean
}

export default function Sidebar({ open }: SidebarProps) {
  return (
    <div
      className={`h-full bg-base-100 z-30 shadow-lg overflow-hidden transition-[width] duration-300 ${
        open ? 'w-64' : 'w-0'
      }`}
    >
      {open && (
        <ul className="menu text-base-content min-h-full w-full p-4">
          <li>
            <Link to="/" className="flex items-center gap-2">
              <HomeIcon className="size-5" />
              Feed
            </Link>
          </li>
          <li>
            <Link to="/map" className="flex items-center gap-2">
              <MapIcon className="size-5" />
              Map
            </Link>
          </li>
          <li>
            <Link to="/friends" className="flex items-center gap-2">
              <UsersIcon className="size-5" />
              Friends
            </Link>
          </li>
          <li>
            <Link to="/groups" className="flex items-center gap-2">
              <UserGroupIcon className="size-5" />
              Groups
            </Link>
          </li>
          <li>
            <Link to="/market" className="flex items-center gap-2">
              <ShoppingBagIcon className="size-5" />
              Market
            </Link>
          </li>
          <li>
            <Link to="/calendar" className="flex items-center gap-2">
              <CalendarIcon className="size-5" />
              Calendar
            </Link>
          </li>
        </ul>
      )}
    </div>
  )
}
