// lib/src/pages/MapPage.tsx
import { useEffect, useRef, useState } from 'react'
import maplibregl, { Map } from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'

interface Location {
  id: number
  coordinates: [number, number]
  title: string
  description: string
}

export default function MapPage() {
  const mapContainer = useRef<HTMLDivElement>(null)
  const map = useRef<Map | null>(null)
  const [locations, setLocations] = useState<Location[]>([])

  useEffect(() => {
    const fetchLocations = async () => {
      try {
        const res = await fetch('/posts.json')
        if (res.ok) {
          const data = await res.json()
          setLocations(data.locations || [])
        }
      } catch (err) {
        console.error('Failed to load locations', err)
      }
    }

    fetchLocations()
  }, [])

  useEffect(() => {
    if (!mapContainer.current) return

    map.current = new maplibregl.Map({
      container: mapContainer.current,
      style: 'https://api.maptiler.com/maps/basic-v2/style.json?key=SD4r2w2iq45jOTGJi0lm',
      center: [10.451526, 51.165691],
      zoom: 5
    })

    map.current.addControl(new maplibregl.NavigationControl(), 'top-right')

    map.current.on('load', () => {
      locations.forEach((loc) => {
        if (map.current) {
          new maplibregl.Marker()
            .setLngLat(loc.coordinates)
            .setPopup(
              new maplibregl.Popup({ offset: 25 })
                .setHTML(`<strong>${loc.title}</strong><p>${loc.description}</p>`)
            )
            .addTo(map.current)
        }
      })
    })

    return () => {
      if (map.current) {
        map.current.remove()
      }
    }
  }, [locations])

  return (
    <div className="h-full flex flex-col">
      <div className="card flex-1 bg-base-100 shadow">
        <div ref={mapContainer} className="h-full w-full rounded-box" style={{ minHeight: '400px' }}></div>
      </div>
    </div>
  )
}

// prototype/src/pages/MapPage.vue
<template>
  <div class="h-full flex flex-col">
    <div class="card flex-1 bg-base-100 shadow">
      <div id="map" class="h-full w-full rounded-box"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import maplibregl, { Map } from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'

let map: Map

interface Location {
  id: number
  coordinates: [number, number]
  title: string
  description: string
}

const locations = ref<Location[]>([])

onMounted(async () => {
  // --- dein Fetch bleibt gleich ---
  try {
    const res = await fetch('/posts.json')
    if (res.ok) {
      const data = await res.json()
      locations.value = data.locations
    }
  } catch (err) {
    console.error('Failed to load locations', err)
  }

  map = new maplibregl.Map({
    container: 'map',
    style: 'https://api.maptiler.com/maps/basic-v2/style.json?key=SD4r2w2iq45jOTGJi0lm',
    center: [10.451526, 51.165691],
    zoom: 5
  })

  map.addControl(new maplibregl.NavigationControl(), 'top-right')

  map.on('load', () => {
    // Entferne Source und Layer für Clustering und Circles
    // -----------------------------------------------
    // map.addSource('places', { … })
    // map.addLayer({ id: 'clusters', … })
    // map.addLayer({ id: 'cluster-count', … })
    // map.addLayer({ id: 'unclustered-point', … })

    // Stattdessen: pro Location einen Marker anlegen
    locations.value.forEach((loc) => {
      // Optional: ein eigenes Icon-Element erstellen
      // const el = document.createElement('div')
      // el.className = 'marker'
      // el.style.backgroundImage = 'url(/marker-icon.png)'
      // el.style.width = '32px'; el.style.height = '32px'

      new maplibregl.Marker(/* el */)          // ohne Argument: Standard-Marker
        .setLngLat(loc.coordinates)
        .setPopup(
          new maplibregl.Popup({ offset: 25 })
            .setHTML(`<strong>${loc.title}</strong><p>${loc.description}</p>`)
        )
        .addTo(map)
    })
  })
})

onUnmounted(() => {
  if (map) {
    map.remove()
  }
})
</script>

<style scoped>
#map {
  min-height: 400px;
}
</style>
