// lib/src/pages/MarketPage.tsx
import { useState, useEffect } from 'react'

interface Item {
  name: string
  price: string
  image: string
}

export default function MarketPage() {
  const [items, setItems] = useState<Item[]>([])

  useEffect(() => {
    const loadItems = async () => {
      try {
        const baseUrl = (window as any).API_BASE_URL || ''
        const res = await fetch(`${baseUrl}/posts.json`)
        if (res.ok) {
          const data = await res.json()
          setItems(data.items || [])
        }
      } catch (err) {
        console.error('Failed to load items', err)
      }
    }

    loadItems()
  }, [])

  return (
    <div className="flex justify-center w-full">
      <div className="grid gap-4 max-w-6xl sm:grid-cols-2 lg:grid-cols-3">
        {items.map((item) => (
          <div
            key={item.name}
            className="card bg-base-100 shadow-sm"
          >
            <figure>
              <img src={item.image} alt={item.name} />
            </figure>
            <div className="card-body">
              <h2 className="card-title">{item.name}</h2>
              <p className="text-primary font-semibold">{item.price}</p>
              <div className="card-actions justify-end">
                <button className="btn btn-sm">Buy</button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// prototype/src/pages/MarketPage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface Item {
  name: string
  price: string
  image: string
}

const items = ref<Item[]>([])

onMounted(async () => {
  try {
    const res = await fetch('/posts.json')
    if (res.ok) {
      const data = await res.json()
      items.value = data.items
    }
  } catch (err) {
    console.error('Failed to load items', err)
  }
})

</script>

<template>
<div class="flex justify-center w-full">


  <div class="grid gap-4 w-6xl sm:grid-cols-2 lg:grid-cols-3">
    <div
      v-for="item in items"
      :key="item.name"
      class="card bg-base-100 shadow-sm"
    >
      <figure><img :src="item.image" :alt="item.name" /></figure>
      <div class="card-body">
        <h2 class="card-title">{{ item.name }}</h2>
        <p class="text-primary font-semibold">{{ item.price }}</p>
        <div class="card-actions justify-end">
          <button class="btn btn-sm">Buy</button>
        </div>
      </div>
    </div>
  </div>
  </div>
</template>
