// lib/src/pages/MessagesPage.tsx
import { useState, useEffect } from 'react'

interface Message {
  from: 'me' | 'them'
  text: string
}

export default function MessagesPage() {
  const [messages, setMessages] = useState<Message[]>([])
  const [newMsg, setNewMsg] = useState('')

  useEffect(() => {
    const loadMessages = async () => {
      try {
        const baseUrl = (window as any).API_BASE_URL || ''
        const res = await fetch(`${baseUrl}/posts.json`)
        if (res.ok) {
          const data = await res.json()
          setMessages(data.messages || [])
        }
      } catch (err) {
        console.error('Failed to load messages', err)
      }
    }

    loadMessages()
  }, [])

  const handleSend = () => {
    if (!newMsg) return
    setMessages(prev => [...prev, { from: 'me', text: newMsg }])
    setNewMsg('')
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSend()
    }
  }

  return (
    <div className="flex flex-col gap-4 h-full">
      <div className="flex-1 overflow-y-auto space-y-2">
        {messages.map((msg, i) => (
          <div
            key={i}
            className={`chat ${msg.from === 'me' ? 'chat-end' : 'chat-start'}`}
          >
            <div className="chat-bubble">{msg.text}</div>
          </div>
        ))}
      </div>
      <div className="join">
        <input
          value={newMsg}
          onChange={(e) => setNewMsg(e.target.value)}
          type="text"
          placeholder="Type a message"
          className="input input-bordered join-item flex-1"
          onKeyPress={handleKeyPress}
        />
        <button className="btn join-item" onClick={handleSend}>
          Send
        </button>
      </div>
    </div>
  )
}

// prototype/src/pages/MessagesPage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'

interface Message {
  from: 'me' | 'them'
  text: string
}

const messages = ref<Message[]>([])

onMounted(async () => {
  try {
    const res = await fetch('/posts.json')
    if (res.ok) {
      const data = await res.json()
      messages.value = data.messages
    }
  } catch (err) {
    console.error('Failed to load messages', err)
  }
})

const newMsg = ref('')

function send() {
  if (!newMsg.value) return
  messages.value.push({ from: 'me', text: newMsg.value })
  newMsg.value = ''
}
</script>

<template>
  <div class="flex flex-col gap-4 h-full">
    <div class="flex-1 overflow-y-auto space-y-2">
      <div
        v-for="(msg, i) in messages"
        :key="i"
        class="chat"
        :class="msg.from === 'me' ? 'chat-end' : 'chat-start'"
      >
        <div class="chat-bubble">{{ msg.text }}</div>
      </div>
    </div>
    <div class="join">
      <input
        v-model="newMsg"
        type="text"
        placeholder="Type a message"
        class="input input-bordered join-item flex-1"
        @keyup.enter="send"
      />
      <button class="btn join-item" @click="send">Send</button>
    </div>
  </div>
</template>
