// app/src/App.tsx
import { useState } from 'react'
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import {
  Navbar,
  Sidebar,
  HomePage,
  MapPage,
  FriendsPage,
  GroupsPage,
  MarketPage,
  CalendarPage,
  ProfilePage,
  SettingsPage,
  MessagesPage
} from '@it4c-design/components'

function App() {
  const [sidebarOpen, setSidebarOpen] = useState(false)

  return (
    <Router>
      <div className="flex h-screen overflow-hidden">
        <div className="flex flex-col flex-1 overflow-hidden">
          <Navbar onToggleSidebar={() => setSidebarOpen(!sidebarOpen)} />
          <div className="flex h-full">
            <Sidebar open={sidebarOpen} />
            <div className="flex-1 bg-base-200 transition-all duration-300 overflow-auto p-4">
              <Routes>
                <Route path="/" element={<HomePage />} />
                <Route path="/map" element={<MapPage />} />
                <Route path="/friends" element={<FriendsPage />} />
                <Route path="/groups" element={<GroupsPage />} />
                <Route path="/market" element={<MarketPage />} />
                <Route path="/calendar" element={<CalendarPage />} />
                <Route path="/profile" element={<ProfilePage />} />
                <Route path="/settings" element={<SettingsPage />} />
                <Route path="/messages" element={<MessagesPage />} />
              </Routes>
            </div>
          </div>
        </div>
      </div>
    </Router>
  )
}

export default App

// prototype/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import Navbar from './components/Navbar.vue'
import Sidebar from './components/Sidebar.vue'

const sidebarOpen = ref(false)
</script>

<template>
  <div class="flex h-screen overflow-hidden">
    <div class="flex flex-col flex-1 overflow-hidden">
      <Navbar @toggle-sidebar="sidebarOpen = !sidebarOpen" />
<div class="flex h-full">
      <Sidebar :open="sidebarOpen" />
      <div
        class="flex-1 bg-base-200 transition-all duration-300 overflow-auto p-4"
      >
        <router-view />
      </div>
    </div>
    </div>
  </div>
</template>

<style scoped>
:root {
  height: 100vh;
}
</style>
